version: 0.0.{build}
skip_tags: true
platform:
  - Any CPU
configuration:
  - Release
before_build:
  - ps: nuget restore
build:
  verbosity: minimal
artifacts:
  - path: KMBEditor\bin\$(configuration)
    name: KMBEditor-v$(appveyor_build_version)
    type: zip
deploy:
  release: KMBEditor Release v$(appveyor_build_version)
  tag: release-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: xpDdb0OSvRlU6PlkMz+pDl+zKB63f0w6vnuekIlI7UBBKHHYOIremWWVTWkYIOpj # your encrypted token from GitHub
  artifact: /.*\.zip/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
