version: 0.0.{build}
platform:
  - Any CPU
configuration:
  - Release
before_build:
  - ps: nuget restore
build:
  verbosity: minimal
artifacts:
  - path: KMBEditor\bin\$(configuration)
    name: KMBEditor
    type: zip